### PR TITLE
added rpc mode decorators

### PR DESCRIPTION
**Pull request by MichaelBelousov**
- tested on a local project,
- supports decorating methods (rpc) and properties (rset) with the same decorators
- JSDoc comments are copied from godot.d.ts's generated comments with minor changes

### CODE REVIEW

**Comment by MichaelBelousov** [comment]
this PR is for issue #31

**Comment by MichaelBelousov** [comment]
[ecmascript-mouse-mode-confined.zip](https://github.com/GodotExplorer/ECMAScript/files/5114535/ecmascript-mouse-mode-confined.zip)

**Review by Geequlim — CHANGES_REQUESTED** [review]
snake_case please

**Comment by MichaelBelousov** [comment]
Will do tomorrow

**Comment by MichaelBelousov** [comment]
Whoops sorry forgot, really busy with moving right now but I will get to this very soon.

**Comment by MichaelBelousov** [comment]
@Geequlim I think that should be good now

**Comment by Geequlim** [comment]
Thanks!

**Pull request merged**
