### PR TITLE
fix build for 3.4

### PR DESCRIPTION
**Pull request by zw7u9tru**
build works for me now.
also updated to work with new scons (it ignores .gen. files now unless added specifically)

I don't know github actions, I tried to add automatic publishing but I am not sure if it works.

Edit:
Added a  file to copy the tests from Godot, this helps reduce the maintenance of the build environments (the previous script was very custom). There is still some specialization, for the ansan and ubsan builds of Linux (fails with Infinity/nan errors) and with windows (quickjs incompatible with msvc, must use mingw.).

I also added a script that should simplify this project's release process, now all you should need to do to update a new release is to tag/create a new release  and everything should be uploaded to the release at the end of the build.

I'm sorry about the amount of commits, I don't know Windows, or JavaScript so there was a lot of trial and error.  As long as we squash merge it should be okay.

### CODE REVIEW

**Comment by zw7u9tru** [comment]
Hello
This is completed now, if you check my forks releases you can see the uploading files action works on tag.  Everything else seems to build well!

Not sure if you have any ideas of how to fix the Linux ubsan errors , but maybe that can be another pr

**Comment by Geequlim** [comment]
Thanks for your contribution!

**Comment by Geequlim** [comment]
We'd better keep the quickjs/quickjs/VERSION.txt

**Comment by zw7u9tru** [comment]
> We'd better keep the quickjs/quickjs/VERSION.txt

Sorry, I don't understand?
I can switch it back to no txt, I was just following the other 3.4 fix pr

**Pull request merged**
